app_home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

app_categories:
    path:     /categories
    defaults: { _controller: AppBundle:Default:listCategories }

app_newCategory:
    path:     /newCategory
    defaults: { _controller: AppBundle:Default:addCategory }

app_resume:
    path:     /resume
    defaults: { _controller: AppBundle:Default:resume }

app_newItem:
    path:     /newItem
    defaults: { _controller: AppBundle:Default:addItem }


