fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_home:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

app_list_categories:
    path:     /categories
    defaults: { _controller: AppBundle:Default:listCategories }

app_delete_category:
    path:     /deleteCategory/{id}
    defaults: { _controller: AppBundle:Default:deleteCategory }

app_delete_item:
    path:     /deleteItem/{id}
    defaults: { _controller: AppBundle:Default:deleteItem }

app_plus_item:
    path:    /add/{id}
    defaults: {_controller: AppBundle:Default:plusItem }

app_decrease_item:
    path:    /decrease/{id}
    defaults: {_controller: AppBundle:Default:decreaseItem }

app_admin:
    path:     /admin
    defaults:  {_controller: AppBundle:Default:admin }